# Generated by Django 2.2.19 on 2021-10-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20211027_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.URLField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
